name: CNSMP

dependencies:
  - python==3.9
  - pytorch
  - pip

  - pip:
      - h5py
      - tensorflow-gpu
      - keras
      - pandas
      - matplotlib
      - bio
      - scikit-learn
      - nltk
      - python-Levenshtein
      - biopython
      - seaborn
      - black