name: CNSMP

dependencies:
  - python==3.10
  - pytorch
  - pip

  - pip:
      - pandas
      - matplotlib
      - bio
      - scikit-learn
      - nltk
      - Levenshtein
      - biopython
      - seaborn
      - black
      - sacrebleu